# Use the official Nginx image from the Docker Hub
FROM nginx:alpine

# Copy custom configuration file from the current directory
# to the Nginx configuration directory in the container
COPY nginx.conf /etc/nginx/nginx.conf